### ISSUE TITLE
Icons Not Working on Latest Vencord Version & Compatibility Issue with Vencord Platform Indicators

### ISSUE THREAD

**Issue by Qu4ntumEl1xir** [MiniDiscordThemes/FluentStatusIcons#7]
The fluent status icons aren't displaying on the latest Vencord version and there seems to be a compatibility issue with the Vencord platform indicators (the platform indicator on DM's list disappears when I have the theme toggled on). 

Fluent Status Icons Not Working: ![image_2024-03-28_235210336](https://github.com/MiniDiscordThemes/FluentStatusIcons/assets/51268365/4ebdd84a-f82c-4c45-a907-dc552ad20d78)

Fluent Status Icons Causing Platform Indicators to Disappear (THEME ON): 
![image_2024-03-28_235349632](https://github.com/MiniDiscordThemes/FluentStatusIcons/assets/51268365/fdf3badd-2cd2-4d28-b50b-0db37a3981ac)

Fluent Status Icons Causing Platform Indicators to Disappear (THEME OFF): 
![image_2024-03-28_235420512](https://github.com/MiniDiscordThemes/FluentStatusIcons/assets/51268365/c34dedad-7682-49bf-aebc-313a51bb7f0e)

**Comment by Saltssaumure** [comment]
This theme is now discontinued.
